create TABLE WA_WORKSTATION(
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    AIRPORT_CODE VARCHAR(3) NOT NULL,
    WAREHOUSE_CODE VARCHAR(10) NOT NULL,
    SECTION VARCHAR(10) NOT NULL,
    TYPE VARCHAR(1) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    COMPATIBLE_TYPES VARCHAR(100),
    SIZE VARCHAR(5),
    SHC VARCHAR(100),
    PRODUCT_TYPE VARCHAR(5),
    OPEN CHAR(1) NOT NULL,
    BREAK_TIME_START TIME WITH TIME ZONE,
    BREAK_TIME_END TIME WITH TIME ZONE,
    SERVICEABLE CHAR(1) NOT NULL,
    MULTIPLE_ULD_ALLOWED CHAR(1) NOT NULL,
    FIXED CHAR(1) NOT NULL,
    NOTIFICATION_TIME VARCHAR(50),
    ACTIVE CHAR(1) NOT NULL,
    PRIMARY KEY (id)
);


create TABLE WA_JOB(
    id INTEGER NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(10) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    START_TIME TIMESTAMP WITH TIME ZONE,
    END_TIME TIMESTAMP WITH TIME ZONE,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    CREATED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP WITH TIME ZONE,
    MODIFIED_BY VARCHAR(50),
    DURATION NUMERIC,
    STATUS CHAR(1) NOT NULL,
    PRIMARY KEY (id)
);


create TABLE WA_JOB_METADATA(
    id INTEGER NOT NULL AUTO_INCREMENT,
    JOB_ID INTEGER NOT NULL,
    KEY VARCHAR(100) NOT NULL,
    VALUE VARCHAR(300) NOT NULL,
    PRIMARY KEY (id)
);