spring:

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    initialization-mode: never
    username: ${BATCH_DB_USERNAME:batch_apps1}
    password: ${BATCH_DB_PASSWORD:batch_apps1}
    url: jdbc:oracle:thin:@${BATCH_DB_IP:10.4.12.78}:${BATCH_DB_PORT:6517}:${BATCH_DB:coxxod12c}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        generate_statistics: true
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write-durations-as-timestamps: false
server:
  error:
    include-message: always

logging:
  level:
    com.accelya.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE